#!/usr/bin/env python3
"""
launch.py  –  One-command launcher for the full privateGPT web stack.
              Now also updates the GitHub Pages widget config automatically.

Steps:
  1. Start Ollama (if not running)
  2. Start Flask API server          (port 5001)
  3. Start Streamlit UI              (port 8501)  — optional
  4. Start Cloudflare Quick Tunnel   -> Flask API
  5. Write tunnel URL into chatbot_public.html AND tunnel-config.js

Usage:
    python launch.py [--port 5001] [--streamlit-port 8501] [--no-streamlit] [--no-tunnel]

Requirements:
    pip install flask flask-cors
    cloudflared on PATH
"""

import argparse, subprocess, sys, os, re, signal, time
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--port",           type=int, default=5001)
parser.add_argument("--streamlit-port", type=int, default=8501)
parser.add_argument("--no-streamlit",   action="store_true")
parser.add_argument("--no-tunnel",      action="store_true")
args = parser.parse_args()

ROOT  = Path(__file__).parent
procs = []

def kill_all(sig=None, frame=None):
    print("\n\n Shutting down...")
    for p in procs:
        try: p.terminate()
        except: pass
    sys.exit(0)

signal.signal(signal.SIGINT,  kill_all)
signal.signal(signal.SIGTERM, kill_all)

def run(cmd, name, **kw):
    print(f"Starting {name}: {' '.join(cmd)}")
    p = subprocess.Popen(cmd, **kw)
    procs.append(p)
    return p

def tail_for_url(proc, pattern, timeout=60):
    deadline = time.time() + timeout
    while time.time() < deadline:
        line = proc.stderr.readline()
        if not line:
            time.sleep(0.1)
            continue
        decoded = line.decode(errors="ignore").strip()
        if decoded:
            print(f"   [tunnel] {decoded}")
        m = re.search(pattern, decoded)
        if m:
            return m.group(0)
    return None

# 1. Ollama
print("\n--- Step 1: Ollama ---")
try:
    import urllib.request
    urllib.request.urlopen("http://localhost:11434", timeout=2)
    print("Ollama already running")
except Exception:
    run(["ollama", "serve"], "Ollama",
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(3)

# 2. Flask API
print("\n--- Step 2: Flask API ---")
env = {**os.environ, "API_PORT": str(args.port)}
run([sys.executable, str(ROOT / "api_server.py")], "Flask API",
    env=env, stdout=sys.stdout, stderr=sys.stderr)
time.sleep(2)

# 3. Streamlit
if not args.no_streamlit:
    print("\n--- Step 3: Streamlit ---")
    run(["streamlit", "run", str(ROOT / "assistant/pvtgpt_cfa_ui.py"),
         f"--server.port={args.streamlit_port}", "--server.headless=true"],
        "Streamlit", stdout=sys.stdout, stderr=sys.stderr)
    time.sleep(3)
    print(f"Streamlit -> http://localhost:{args.streamlit_port}")

# 4. Cloudflare tunnel
tunnel_url = None
if not args.no_tunnel:
    print("\n--- Step 4: Cloudflare Tunnel ---")
    tun = run(
        ["cloudflared", "tunnel", "--url", f"http://localhost:{args.port}", "--no-autoupdate"],
        "cloudflared",
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    tunnel_url = tail_for_url(tun, r"https://[a-zA-Z0-9\-]+\.trycloudflare\.com")

    if tunnel_url:
        print(f"\nPublic URL: {tunnel_url}\n")

        # 4a. Patch chatbot_public.html
        html_src = ROOT / "chatbot.html"
        if html_src.exists():
            html = html_src.read_text()
            (ROOT / "chatbot_public.html").write_text(
                html.replace('const API_BASE = "";', f'const API_BASE = "{tunnel_url}";')
            )
            print("chatbot_public.html updated")

        # 4b. Write tunnel-config.js for the GitHub Pages widget
        cfg_js = ROOT / "js" / "tunnel-config.js"
        cfg_js.parent.mkdir(exist_ok=True)
        cfg_js.write_text(
            f"/* Auto-generated by launch.py -- do not edit manually */\n"
            f"window.PGPT_API_BASE = \"{tunnel_url}\";\n"
        )
        print(f"js/tunnel-config.js written")
        print()
        print("  To embed on baridhi.github.io:")
        print("  1. Copy js/pgpt-widget.js  -> baridhi.github.io/js/")
        print("  2. Copy js/tunnel-config.js -> baridhi.github.io/js/  (do this each time you restart)")
        print("  3. index.html already has the <script> tags (see GUIDE.md)")
        print("  4. git add js/tunnel-config.js && git commit -m 'update tunnel URL' && git push")
    else:
        print("Could not detect tunnel URL.")

# Summary
print("\n" + "="*60)
print("  PRIVATGPT STACK RUNNING")
print("="*60)
print(f"  Flask API       ->  http://localhost:{args.port}")
if not args.no_streamlit:
    print(f"  Streamlit UI    ->  http://localhost:{args.streamlit_port}")
if tunnel_url:
    print(f"  Public (tunnel) ->  {tunnel_url}")
print("="*60)
print("  Ctrl+C to stop everything.\n")

for p in procs:
    p.wait()
