/**
 * pgpt-widget.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Drop-in PrivateGPT chat widget for baridhi.github.io (or any static site).
 *
 * Usage — add ONE line before </body> in index.html:
 *
 *   <script
 *     src="js/pgpt-widget.js"
 *     data-api="https://YOUR-TUNNEL.trycloudflare.com"
 *     data-title="Ask My Research"
 *     data-greeting="Hi! Ask me anything about Baridhi's research papers."
 *   ></script>
 *
 * Attributes
 *   data-api       (required) Cloudflare tunnel base URL — no trailing slash
 *   data-title     Widget header text (default: "Research Assistant")
 *   data-greeting  First bot message (default shown below)
 *   data-accent    Hex accent color   (default: #2c3e7a — navy to match the site)
 *   data-position  "right" | "left"   (default: "right")
 * ─────────────────────────────────────────────────────────────────────────────
 */
(function () {
  "use strict";

  /* ── Read config from <script> tag ─────────────────────────────────────── */
  const scriptEl   = document.currentScript;
  // If data-api-from-config="true", read the URL from window.PGPT_API_BASE
  // (set by tunnel-config.js which is generated by launch.py).
  // Otherwise fall back to the inline data-api attribute.
  const _rawApi = scriptEl.dataset.apiFromConfig === "true"
    ? (window.PGPT_API_BASE || "")
    : (scriptEl.dataset.api || "");
  const API_BASE   = _rawApi.replace(/\/$/, "");
  const TITLE      = scriptEl.dataset.title    || "Research Assistant";
  const GREETING   = scriptEl.dataset.greeting ||
    "Hi! I'm Baridhi's research assistant — powered by a private local LLM. " +
    "Ask me about the papers, data, or methods on this site.";
  const ACCENT     = scriptEl.dataset.accent   || "#2c3e7a";
  const POSITION   = scriptEl.dataset.position === "left" ? "left" : "right";

  if (!API_BASE) {
    console.warn("[pgpt-widget] data-api attribute is missing — widget disabled.");
    return;
  }

  /* ── Inject CSS ─────────────────────────────────────────────────────────── */
  const css = `
  #pgpt-fab {
    position: fixed;
    bottom: 28px;
    ${POSITION}: 28px;
    z-index: 9998;
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: ${ACCENT};
    color: #fff;
    border: none;
    cursor: pointer;
    box-shadow: 0 4px 18px rgba(0,0,0,0.28);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 24px;
    transition: transform 0.2s, box-shadow 0.2s;
    outline: none;
  }
  #pgpt-fab:hover { transform: scale(1.08); box-shadow: 0 6px 24px rgba(0,0,0,0.34); }
  #pgpt-fab .pgpt-badge {
    position: absolute;
    top: 2px;
    right: 2px;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: #4ade80;
    border: 2px solid #fff;
    display: none;
  }
  #pgpt-fab .pgpt-badge.visible { display: block; }

  #pgpt-panel {
    position: fixed;
    bottom: 96px;
    ${POSITION}: 18px;
    z-index: 9999;
    width: 370px;
    max-width: calc(100vw - 36px);
    height: 520px;
    max-height: calc(100vh - 120px);
    border-radius: 18px;
    box-shadow: 0 12px 48px rgba(0,0,0,0.22);
    display: flex;
    flex-direction: column;
    overflow: hidden;
    background: #fff;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    font-size: 14px;
    opacity: 0;
    transform: translateY(16px) scale(0.97);
    pointer-events: none;
    transition: opacity 0.22s ease, transform 0.22s ease;
  }
  #pgpt-panel.open {
    opacity: 1;
    transform: translateY(0) scale(1);
    pointer-events: all;
  }

  /* header */
  #pgpt-header {
    background: ${ACCENT};
    color: #fff;
    padding: 14px 16px 12px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-shrink: 0;
  }
  #pgpt-header-left { display: flex; align-items: center; gap: 10px; }
  #pgpt-header-icon {
    width: 32px; height: 32px;
    background: rgba(255,255,255,0.18);
    border-radius: 8px;
    display: flex; align-items: center; justify-content: center;
    font-size: 16px;
  }
  #pgpt-header-title { font-weight: 700; font-size: 15px; }
  #pgpt-header-sub   { font-size: 11px; opacity: 0.75; margin-top: 1px; }
  #pgpt-close {
    background: none; border: none; color: #fff;
    cursor: pointer; font-size: 22px; line-height: 1;
    opacity: 0.8; padding: 0;
  }
  #pgpt-close:hover { opacity: 1; }

  /* messages */
  #pgpt-messages {
    flex: 1;
    overflow-y: auto;
    padding: 16px 14px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    background: #f7f8fc;
  }
  #pgpt-messages::-webkit-scrollbar { width: 3px; }
  #pgpt-messages::-webkit-scrollbar-thumb { background: #dde; border-radius: 99px; }

  .pgpt-msg {
    display: flex;
    gap: 8px;
    animation: pgptFade 0.2s ease;
  }
  @keyframes pgptFade {
    from { opacity: 0; transform: translateY(6px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  .pgpt-msg.user  { flex-direction: row-reverse; }
  .pgpt-avatar {
    width: 28px; height: 28px; border-radius: 7px;
    display: flex; align-items: center; justify-content: center;
    font-size: 14px; flex-shrink: 0;
  }
  .pgpt-msg.bot  .pgpt-avatar { background: ${ACCENT}22; }
  .pgpt-msg.user .pgpt-avatar { background: #e8eaf6; }
  .pgpt-bubble {
    max-width: 82%;
    padding: 9px 13px;
    border-radius: 13px;
    line-height: 1.55;
    white-space: pre-wrap;
    word-break: break-word;
    font-size: 13.5px;
  }
  .pgpt-msg.bot  .pgpt-bubble {
    background: #fff;
    border: 1px solid #e4e6ef;
    border-top-left-radius: 3px;
    color: #1a1a2e;
  }
  .pgpt-msg.user .pgpt-bubble {
    background: ${ACCENT};
    color: #fff;
    border-top-right-radius: 3px;
  }
  .pgpt-sources {
    margin-top: 7px;
    font-size: 11px;
    color: #888;
    display: flex; flex-wrap: wrap; gap: 4px; align-items: center;
  }
  .pgpt-src-tag {
    background: #f0f0f8;
    border: 1px solid #dde;
    padding: 1px 7px;
    border-radius: 99px;
    font-size: 10.5px;
  }

  /* typing dots */
  .pgpt-dots { display: flex; gap: 4px; align-items: center; padding: 2px 0; }
  .pgpt-dots span {
    width: 6px; height: 6px; border-radius: 50%;
    background: ${ACCENT};
    animation: pgptPulse 1.1s infinite ease-in-out;
  }
  .pgpt-dots span:nth-child(2) { animation-delay: 0.18s; }
  .pgpt-dots span:nth-child(3) { animation-delay: 0.36s; }
  @keyframes pgptPulse {
    0%,80%,100% { transform:scale(0.65); opacity:0.5; }
    40%         { transform:scale(1);    opacity:1;   }
  }

  /* input */
  #pgpt-inputbar {
    display: flex;
    gap: 8px;
    padding: 10px 12px;
    border-top: 1px solid #e8e9f0;
    background: #fff;
    align-items: flex-end;
    flex-shrink: 0;
  }
  #pgpt-input {
    flex: 1;
    border: 1px solid #dde;
    border-radius: 10px;
    padding: 8px 12px;
    font-size: 13.5px;
    font-family: inherit;
    resize: none;
    outline: none;
    max-height: 100px;
    overflow-y: auto;
    line-height: 1.45;
    color: #1a1a2e;
    background: #f7f8fc;
    transition: border-color 0.18s;
  }
  #pgpt-input:focus { border-color: ${ACCENT}; background: #fff; }
  #pgpt-input::placeholder { color: #aab; }
  #pgpt-send {
    width: 36px; height: 36px;
    background: ${ACCENT};
    border: none;
    border-radius: 9px;
    cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    color: #fff;
    font-size: 15px;
    flex-shrink: 0;
    transition: opacity 0.18s;
  }
  #pgpt-send:hover   { opacity: 0.85; }
  #pgpt-send:disabled { opacity: 0.35; cursor: not-allowed; }

  /* powered-by footer */
  #pgpt-footer {
    text-align: center;
    font-size: 10.5px;
    color: #bbb;
    padding: 5px;
    background: #fff;
    border-top: 1px solid #f0f0f0;
    flex-shrink: 0;
  }
  #pgpt-footer a { color: #bbb; text-decoration: none; }
  #pgpt-footer a:hover { text-decoration: underline; }

  /* offline banner */
  #pgpt-offline {
    background: #fff3cd;
    border-bottom: 1px solid #ffc107;
    color: #856404;
    font-size: 12px;
    padding: 6px 14px;
    display: none;
    align-items: center;
    gap: 6px;
    flex-shrink: 0;
  }
  #pgpt-offline.show { display: flex; }
  `;

  const style = document.createElement("style");
  style.textContent = css;
  document.head.appendChild(style);

  /* ── Build HTML ─────────────────────────────────────────────────────────── */
  document.body.insertAdjacentHTML("beforeend", `
    <button id="pgpt-fab" aria-label="Open Research Assistant" title="${TITLE}">
      🤖<span class="pgpt-badge" id="pgpt-badge"></span>
    </button>

    <div id="pgpt-panel" role="dialog" aria-label="${TITLE}">
      <div id="pgpt-header">
        <div id="pgpt-header-left">
          <div id="pgpt-header-icon">🔒</div>
          <div>
            <div id="pgpt-header-title">${TITLE}</div>
            <div id="pgpt-header-sub" id="pgpt-status-text">Connecting…</div>
          </div>
        </div>
        <button id="pgpt-close" aria-label="Close">✕</button>
      </div>

      <div id="pgpt-offline">⚠️ API offline — make sure your laptop tunnel is running.</div>

      <div id="pgpt-messages"></div>

      <div id="pgpt-inputbar">
        <textarea id="pgpt-input" rows="1"
          placeholder="Ask a question…"
          aria-label="Your question"></textarea>
        <button id="pgpt-send" aria-label="Send">➤</button>
      </div>

      <div id="pgpt-footer">
        Powered by <a href="https://github.com/baridhi/privateGPT_cfa" target="_blank">PrivateGPT</a>
        · runs locally on your laptop
      </div>
    </div>
  `);

  /* ── Refs ───────────────────────────────────────────────────────────────── */
  const fab        = document.getElementById("pgpt-fab");
  const panel      = document.getElementById("pgpt-panel");
  const closeBtn   = document.getElementById("pgpt-close");
  const messages   = document.getElementById("pgpt-messages");
  const input      = document.getElementById("pgpt-input");
  const sendBtn    = document.getElementById("pgpt-send");
  const badge      = document.getElementById("pgpt-badge");
  const offlineBanner = document.getElementById("pgpt-offline");
  const statusText = document.getElementById("pgpt-header-sub");

  let open     = false;
  let online   = false;
  let msgId    = 0;
  let hasGreeted = false;

  /* ── Toggle panel ───────────────────────────────────────────────────────── */
  function togglePanel() {
    open = !open;
    panel.classList.toggle("open", open);
    fab.innerHTML = open ? `✕<span class="pgpt-badge ${online ? "visible" : ""}" id="pgpt-badge"></span>`
                         : `🤖<span class="pgpt-badge ${online ? "visible" : ""}" id="pgpt-badge"></span>`;
    if (open && !hasGreeted) {
      appendBotMsg(GREETING, []);
      hasGreeted = true;
      input.focus();
    }
  }

  fab.addEventListener("click", togglePanel);
  closeBtn.addEventListener("click", togglePanel);

  /* Close on Escape */
  document.addEventListener("keydown", e => { if (e.key === "Escape" && open) togglePanel(); });

  /* ── Health check ───────────────────────────────────────────────────────── */
  async function checkHealth() {
    try {
      const r = await fetch(`${API_BASE}/health`, { signal: AbortSignal.timeout(5000) });
      const d = await r.json();
      const ok = d.status === "ok";
      setOnline(ok, ok ? (d.model || "ready") : "degraded");
    } catch {
      setOnline(false, "Offline");
    }
  }

  function setOnline(isOnline, txt) {
    online = isOnline;
    statusText.textContent = isOnline ? `● ${txt}` : `○ ${txt}`;
    statusText.style.color = isOnline ? "#a8f0c6" : "#ffa07a";
    offlineBanner.classList.toggle("show", !isOnline);
    // sync badge (re-query since fab innerHTML replaced)
    document.querySelectorAll(".pgpt-badge").forEach(b => {
      b.classList.toggle("visible", isOnline);
    });
  }

  checkHealth();
  setInterval(checkHealth, 20_000);

  /* ── Messaging ──────────────────────────────────────────────────────────── */
  function esc(s) {
    return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  }

  function appendMsg(role, html) {
    const id = `pgpt-${++msgId}`;
    const avatar = role === "user" ? "🧑" : "🤖";
    const div = document.createElement("div");
    div.className = `pgpt-msg ${role}`;
    div.id = id;
    div.innerHTML = `<div class="pgpt-avatar">${avatar}</div><div class="pgpt-bubble">${html}</div>`;
    messages.appendChild(div);
    messages.scrollTop = messages.scrollHeight;
    return id;
  }

  function appendBotMsg(text, sources) {
    const srcHtml = sources && sources.length
      ? `<div class="pgpt-sources">Sources: ${sources.map(s=>`<span class="pgpt-src-tag">${esc(s)}</span>`).join("")}</div>`
      : "";
    return appendMsg("bot", esc(text) + srcHtml);
  }

  function appendTyping() {
    return appendMsg("bot", `<div class="pgpt-dots"><span></span><span></span><span></span></div>`);
  }

  function removeMsg(id) {
    document.getElementById(id)?.remove();
  }

  /* ── Send ───────────────────────────────────────────────────────────────── */
  async function send() {
    const q = input.value.trim();
    if (!q) return;
    appendMsg("user", esc(q));
    input.value = "";
    input.style.height = "auto";
    sendBtn.disabled = true;

    const typId = appendTyping();

    try {
      const r = await fetch(`${API_BASE}/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: q }),
        signal: AbortSignal.timeout(120_000),   // LLM can be slow
      });
      const d = await r.json();
      removeMsg(typId);
      if (d.error) appendBotMsg(`⚠️ ${d.error}`, []);
      else appendBotMsg(d.answer, d.sources || []);
    } catch (e) {
      removeMsg(typId);
      appendBotMsg("⚠️ No response from the API. Is the tunnel running?", []);
    } finally {
      sendBtn.disabled = false;
      input.focus();
    }
  }

  sendBtn.addEventListener("click", send);
  input.addEventListener("keydown", e => {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); }
  });
  input.addEventListener("input", function () {
    this.style.height = "auto";
    this.style.height = Math.min(this.scrollHeight, 100) + "px";
  });

})();
